name: 'KiBot'
description: 'auto generate exports (schematics, gerbers, plots) for any KiCad project.'
author: 'Salvador E. Tropea'
inputs:
  config:
    description: 'The plotting config file to use'
    required: true
  dir:
    description: 'The output directory [default: .]'
    required: false
    default: '.'
  board:
    description: 'The PCB .kicad-pcb board file [default: first *.kicad_pcb found]'
    required: false
    default: '__SCAN__'
  schema:
    description: 'The schematic file (.sch) [default: first *.*sch found]'
    required: false
    default: '__SCAN__'
  skip:
    description: 'Skip preflights, comma separated or "all" [default: no skip]'
    required: false
    default: '__NONE__'
  variant:
    description: 'Global variant to use [default: no variants]'
    required: false
    default: '__NONE__'
  verbose:
    description: 'Verbosity level [default: 0]'
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    -  -c ${{ inputs.config }}
    -  -d ${{ inputs.dir }}
    -  -b ${{ inputs.board }}
    -  -e ${{ inputs.schema }}
    -  -s ${{ inputs.skip }}
    -  -v ${{ inputs.verbose }}
    -  -V ${{ inputs.variant }}
branding:
  icon: 'cpu'
  color: 'green'
