# This workflow will create the development docker images

name: Create `dev` images

on:
  workflow_dispatch

jobs:
  push_to_registry_ki5:
    strategy:
      matrix:
        ki_release: [dev_image_k5, dev_image_k6, dev_image_k7, dev_image_k5f, dev_image_k6f, dev_image_k7f]

    name: Docker ${{ matrix.ki_release }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    # Don't create `dev` images using the `master`
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd kibot/tools/${{ matrix.ki_release }}
        ./build.sh
